require_relative 'chess'
require_relative 'board'
require_relative 'position'
require_relative 'move'
require_relative 'player'
require_relative 'validation'
require_relative 'execute_move'
require_relative 'game_result'

require_relative './pieces/piece'
require_relative './pieces/pawn'
require_relative './pieces/white_pawn'
require_relative './pieces/black_pawn'
require_relative './pieces/rook'
require_relative './pieces/knight'
require_relative './pieces/bishop'
require_relative './pieces/queen'
require_relative './pieces/king'
